var WS=function(ha,V){function W(){var a=ia.value,f=I(ja),c=I(ka),m=I(la),r=I(ma),j,h;j=!0===C.checked?C.value:!0===D.checked?D.value:!0===E.checked?E.value:F.value;h=!0===X.selected?X.value:!0===Y.selected?Y.value:!0===Z.selected?Z.value:na.value;$={};z=(new Date).getTime();A=J=0;oa.innerHTML="0/0";aa.innerHTML=Ba;d=b("e");d.style.display="block";pa.className="n";K&&(k("query",a),k("atonly",f),k("lionly",c),k("strict",m),k("nonstop",r),k("range",j),k("period",h));if(""!==h){var x=Ca;switch(h){case "w":x*=
7;break;case "m":x*=30}h=z-x}if(a){x="ig";m&&(x="g");for(var a=a.replace(/\u3000/g," ").replace(/^\s+|\s+$/g," ").split(" "),e=0,g=a.length;e<g;e++)a[e]=RegExp("("+L(a[e]).replace(/([\\|\(|\)|\{|\}|\[|\]|\.|\^|\||\+|\*|\?|\$])/g,"\\$1")+")",x)}a={ec:0,sc:0,bc:0,atonly:f,lionly:c,strict:m,nonstop:r,range:j,period:h,word:a,q:M[j],qid:z};"star"!==j?N(a,!1):(j=(j=s("star"))?w.parse(j):{},Da(j,a,Math.floor(z/1E3)));return!1}function qa(a,f){if(z===f.qid){var c="",m="",r="",j=f.word,h=0,g,e,v,d,t,n,k,y,
i,p,u,l,q;for(g in a){e=a[g];i=e.user;v=L(e.message);n={};k=y="";p=!0;e.attachment&&(n=e.attachment,k=L(n.name),y=L(n.description),d=n.media);i&&(m=i.name,r=i.profile_url);if(1==f.atonly&&!k&&!y&&!d||1==f.lionly&&e.likes&&!e.likes.user_likes||f.period>1E3*e.created_time)p=!1;else if(""!==j[0]){t=v+k+y;i&&i.name&&(t+=i.name);if(e.comments){i=e.comments.comment_list;l="";u=0;for(q=i.length;u<q;u++)l+=" "+i[u].text;t+=l}u=0;for(q=j.length;u<q;u++)if(i=j[u],t.match(i))v=v.replace(i,G),k=k.replace(i,G),
y=y.replace(i,G),l=l.replace(i,G),m=m.replace(i,G);else{p=!1;break}}if(p){$[e.post_id]=e;t=p="";u=i=e.permalink;n&&n.properties&&(d[0]?(d=d[0],i=d.href,t=B[0]+i+B[1]+d.src+B[2]+i+B[3]+k+B[4]+y+B[5]):(i=e.attachment.href,t=O[0]+i+O[1]+k+O[2]+y+O[3]));"star"!==f.range&&(p=ba[0]+e.post_id+ba[1],p=e.likes.user_likes?p+P:p+S,p+=ba[2]);n=new Date(1E3*e.created_time);c+=o[0]+e.actor_id+o[1]+r+o[2]+m+o[3]+v+o[4]+t+o[5]+l+o[6]+n.getFullYear()+"/"+H(n.getMonth()+1)+"/"+H(n.getDate())+" "+H(n.getHours())+":"+
H(n.getMinutes())+":"+H(n.getSeconds())+o[7]+u+o[8]+i+o[9]+p+o[10];if(ca){if(v=s("star"))v=w.parse(v),v[e.post_id]&&(c+=" o");c+=o[11]+e.post_id+o[12]}h++}}J+=a.length;c&&(A+=h,m=f.range+A,r=V.createElement("div"),r.id=m,r.className="wc",r.innerHTML=c,aa.insertBefore(r,aa.lastChild),da(b(m)));oa.innerHTML=A+"/"+J;f.sc=A;return g}}function Da(a,f){var c=0,m=[],b;for(b in a)m[c]=a[b],c++;m.sort(function(a,f){return a.created_time<f.created_time?1:-1});setTimeout(function(){qa(m,f);ea()},100)}function N(a,
f){if(z===a.qid){var c=a.q;f&&(c+=" AND created_time<"+f);FB.api({method:"fql.multiquery",queries:{q1:c,q2:"select uid,name,profile_url from user where uid IN(select actor_id from #q1)"}},function(c){if(c.error_msg)return!1;if(z===a.qid){var b=c[0].fql_result_set;if(b.length){var j=c[1].fql_result_set,c={},h,d;h=0;for(d=b.length;h<d;h++)g[a.range][b[h].post_id]=b[h];h=0;for(d=j.length;h<d;h++)c[j[h].uid]=j[h];ca&&w.parse(w.stringify(g[a.range]));for(h in b)j=b[h],j.user=c[j.actor_id];var e=qa(b,a);
a.ec=0;!a.nonstop&&10<=a.sc-a.bc?(a.bc=a.sc,a.last_time=b[e].created_time,ea(a)):setTimeout(function(){N(a,b[e].created_time)},500)}else 5>a.ec?(a.ec++,setTimeout(function(){N(a,f)},500)):ea()}})}}function ea(a){d.style.display="block";d.className="";d.innerHTML=ra;pa.className="";a&&a.last_time?d.onclick=function(){var f=a.last_time;delete a.last_time;N(a,f);delete d.onclick;d.className="n";d.innerHTML=sa}:(d.innerHTML=ta,d.className="e")}function s(a){return K["wallsearch-"+a]}function k(a,f){K["wallsearch-"+
a]=f}function H(a){return 10>1*a?"0"+a:a}function L(a){return a?a.replace(/<|>/g,function(a){return{"<":"&lt;",">":"&gt;"}[a]}):""}function I(a){return!0===a.checked?a.value:""}function b(a){return V.getElementById(a)}function da(a,f){a.style.height="auto";var c=a.scrollHeight;a.style.height="0";ua(a,"height",c,0,f)}function ua(a,f,c,b,d){var g=1*new Date,h=a.style,k=setInterval(function(){var a=new Date-g,l=c*a/70+b;70<a&&(clearInterval(k),l=b+c,d&&setTimeout(function(){d()},10));h[f]=l+"px"},10)}
(function(a){var b=a.createElement("script");b.id="facebook-jssdk";b.async=!0;b.src="//connect.facebook.net/en_US/all.js";a.getElementsByTagName("head")[0].appendChild(b)})(V);ha.fbAsyncInit=function(){FB.init({appId:"168589393194273",channelUrl:"//atms.sakura.ne.jp/amidawars/index.php",status:!0,cookie:!0,xfbml:!0});var a=b("s");da(a,function(){a.style.overflow="visible"});Q&&W()};var aa=b("w"),oa=b("o"),ia=b("q"),pa=b("b"),T=b("d"),C=b("rm"),D=b("rf"),E=b("ra"),F=b("rs"),va=b("lm"),wa=b("lf"),xa=
b("la"),ya=b("ls"),l=va,X=b("pn"),Y=b("ph"),Z=b("pw"),na=b("pm"),ja=b("ao"),ka=b("lo"),la=b("os"),ma=b("ns"),d,ra="\u3082\u3063\u3068\u691c\u7d22\u3059\u308b",ta="\u691c\u7d22\u304c\u7d42\u4e86\u3057\u307e\u3057\u305f",S="\u3044\u3044\u306d\uff01",P="\u3044\u3044\u306d\u3092\u53d6\u308a\u6d88\u3059",za="\u3044\u3044\u306d\uff01\u306b\u5931\u6557\u3057\u307e\u3057\u305f\u3002\u6642\u9593\u3092\u7f6e\u3044\u3066\u3082\u3046\u4e00\u5ea6\u304a\u8a66\u3057\u304f\u3060\u3055\u3044\u3002",A,J,z,$,g={me:{},
friends:{},all:{}},o='<article><img src="https://graph.facebook.com/,/picture" class="i" /><div><h2><a href="," target="_blank">,</a></h2><p>,</p>,<aside>,</aside><time>,</time><nav>\u00b7 <a href="," target="_blank" class="u">\u3082\u3063\u3068\u898b\u308b</a>\u00b7 <a href="http://www.facebook.com/sharer.php?u=," target="_blank" class="u">\u30b7\u30a7\u30a2</a>,</nav></div><a class="s," title="\u661f" name="," onclick="WS.star(this)">\u2605</a></article>'.split(","),ba=['\u00b7 <a href="javascript:void(0);" onclick="WS.like(\'',
"',this);\">","</a>"],B='<blockquote><a href="," target="_blank" class="h"><img src="," /></a><div><h3><a href="," target="_blank">,</a></h3><p>,</p></div></blockquote>'.split(","),O=['<blockquote><h2><a href="','" target="_blank">',"</a></h2><p>","</p></blockquote>"],G="<mark>$1</mark>",sa='<span class="a c"><span class="a1"></span><span class="a2"></span><span class="a3"></span></span>',Ba='<p id="e">'+sa+"</p>",Aa={"delete":S,post:P},M={me:'=me() AND permalink!=""',friends:"in(SELECT target_id FROM connection WHERE source_id=me())AND source_id!=me()",
all:"in(SELECT target_id FROM connection WHERE source_id=me())"},q,Ca=864E5,ca=!0,w=JSON,K=ha.localStorage,fa=!1;"ja_JP"!==LA&&(ra="More",ta="Search Exit.",S="Like",P="unlike",za="Like Failed. Please try again at intervals.",Aa={"delete":S,post:P});for(q in M)M[q]="SELECT post_id,actor_id,message,created_time,permalink,attachment,comments,likes FROM stream WHERE source_id "+M[q]+" AND is_hidden=0";if(K&&"object"===typeof w&&w.stringify&&w.parse){q=s("query");var U=s("range"),ga=s("period");Q&&(q=
Q);R&&(U=R);q&&(ia.value=q);if(U&&"me"!==U)switch(C.checked=!1,U){case "friends":D.checked=!0;l=wa;break;case "all":E.checked=!0;l=xa;break;default:F.checked=!0,l=ya}l.className="t";if(ga&&""!==ga)switch(X.selected=!1,ga){case "h":Y.selected=!0;break;case "w":Z.selected=!0;break;default:na.selected=!0}1==s("atonly")&&(ja.checked=!0);1==s("lionly")&&(ka.checked=!0);1==s("strict")&&(la.checked=!0);1==s("nonstop")&&(ma.checked=!0)}else ca=!1,F.disabled=!0,o[10]="</div></div></div></li>";b("y").onclick=
W;C.t=va;D.t=wa;E.t=xa;F.t=ya;C.onclick=D.onclick=E.onclick=F.onclick=function(){W();l.className="";l=this.t;l.className="t"};b("v").onclick=function(){if(fa===false){fa=true;da(T)}else{fa=false;ua(T,"height",-T.scrollHeight,T.scrollHeight,void 0)}};(function(a){if(a)a.onclick=function(){location.hash=a.href;location.hash="";return false}})(b("pt"));return{like:function(a,b,c){b.disabled=true;if(g.me[a])c=g.me[a].likes.user_likes;else if(g.friends[a])c=g.friends[a].likes.user_likes;else if(g.all[a])c=
g.all[a].likes.user_likes;c=c===true?"delete":"post";FB.api("/"+a+"/likes",c,function(d){if(d&&!d.error){b.innerHTML=Aa[c];if(g.me[a])g.me[a].likes.user_likes=!g.me[a].likes.user_likes;if(g.friends[a])g.friends[a].likes.user_likes=!g.friends[a].likes.user_likes;if(g.all[a])g.all[a].likes.user_likes=!g.all[a].likes.user_likes}else alert(za);b.disabled=false});return false},star:function(a){var b=s("star"),c=a.name,b=b?w.parse(b):{};if(a.className==="s"){a.className="s o";b[c]=$[c]}else{a.className=
"s";delete b[c]}k("star",w.stringify(b))}}}(window,document);
