var WS=function(ma,W){function X(){var a=na.value,f=E(oa),c=E(pa),m=E(qa),r=E(ra),j,h;j=!0===F.checked?F.value:!0===G.checked?G.value:!0===H.checked?H.value:I.value;h=!0===Y.selected?Y.value:!0===Z.selected?Z.value:!0===$.selected?$.value:sa.value;aa={};z=(new Date).getTime();A=J=0;ta.innerHTML="0/0";ba.innerHTML=Ca;d=b("e");d.style.display="block";ua.className="n";K&&(k("query",a),k("atonly",f),k("lionly",c),k("strict",m),k("nonstop",r),k("range",j),k("period",h));if(""!==h){var x=Da;switch(h){case "w":x*=
7;break;case "m":x*=30}h=z-x}if(a){x="ig";m&&(x="g");for(var a=a.replace(/\u3000/g," ").replace(/^\s+|\s+$/g," ").split(" "),e=0,g=a.length;e<g;e++)a[e]=RegExp("("+L(a[e]).replace(/([\\|\(|\)|\{|\}|\[|\]|\.|\^|\||\+|\*|\?|\$])/g,"\\$1")+")",x)}a={ec:0,sc:0,bc:0,atonly:f,lionly:c,strict:m,nonstop:r,range:j,period:h,word:a,q:M[j],qid:z};"star"!==j?N(a,!1):(j=(j=s("star"))?w.parse(j):{},Ea(j,a,Math.floor(z/1E3)));return!1}function va(a,f){if(z===f.qid){var c="",m="",r="",j=f.word,h=0,g,e,v,d,t,n,k,y,
i,p,u,l,q;for(g in a){e=a[g];i=e.user;v=L(e.message);n={};k=y="";p=!0;e.attachment&&(n=e.attachment,k=L(n.name),y=L(n.description),d=n.media);i&&(m=i.name,r=i.profile_url);if(1==f.atonly&&!k&&!y&&!d||1==f.lionly&&e.likes&&!e.likes.user_likes||f.period>1E3*e.created_time)p=!1;else if(""!==j[0]){t=v+k+y;i&&i.name&&(t+=i.name);if(e.comments){i=e.comments.comment_list;l="";u=0;for(q=i.length;u<q;u++)l+=" "+i[u].text;t+=l}u=0;for(q=j.length;u<q;u++)if(i=j[u],t.match(i))v=v.replace(i,C),k=k.replace(i,C),
y=y.replace(i,C),l=l.replace(i,C),m=m.replace(i,C);else{p=!1;break}}if(p){aa[e.post_id]=e;t=p="";u=i=e.permalink;n&&n.properties&&(d[0]?(d=d[0],i=d.href,t=B[0]+i+B[1]+d.src+B[2]+i+B[3]+k+B[4]+y+B[5]):(i=e.attachment.href,t=O[0]+i+O[1]+k+O[2]+y+O[3]));"star"!==f.range&&(p=ca[0]+e.post_id+ca[1],p=e.likes.user_likes?p+P:p+S,p+=ca[2]);n=new Date(1E3*e.created_time);c+=o[0]+e.actor_id+o[1]+r+o[2]+m+o[3]+v+o[4]+t+o[5]+l+o[6]+n.getFullYear()+"/"+D(n.getMonth()+1)+"/"+D(n.getDate())+" "+D(n.getHours())+":"+
D(n.getMinutes())+":"+D(n.getSeconds())+o[7]+u+o[8]+i+o[9]+p+o[10];if(da){if(v=s("star"))v=w.parse(v),v[e.post_id]&&(c+=" o");c+=o[11]+e.post_id+o[12]}h++}}J+=a.length;c&&(A+=h,m=f.range+A,r=W.createElement("div"),r.id=m,r.className="wc",r.innerHTML=c,ba.insertBefore(r,ba.lastChild),ea(b(m)));ta.innerHTML=A+"/"+J;f.sc=A;return g}}function Ea(a,f){var c=0,m=[],b;for(b in a)m[c]=a[b],c++;m.sort(function(a,f){return a.created_time<f.created_time?1:-1});setTimeout(function(){va(m,f);fa()},100)}function N(a,
f){if(z===a.qid){var c=a.q;f&&(c+=" AND created_time<"+f);FB.api({method:"fql.multiquery",queries:{q1:c,q2:"select uid,name,profile_url from user where uid IN(select actor_id from #q1)"}},function(c){if(c.error_msg)return!1;if(z===a.qid){var b=c[0].fql_result_set;if(b.length){var j=c[1].fql_result_set,c={},h,d;h=0;for(d=b.length;h<d;h++)g[a.range][b[h].post_id]=b[h];h=0;for(d=j.length;h<d;h++)c[j[h].uid]=j[h];da&&w.parse(w.stringify(g[a.range]));for(h in b)j=b[h],j.user=c[j.actor_id];var e=va(b,a);
a.ec=0;!a.nonstop&&10<=a.sc-a.bc?(a.bc=a.sc,a.last_time=b[e].created_time,fa(a)):setTimeout(function(){N(a,b[e].created_time)},500)}else 5>a.ec?(a.ec++,setTimeout(function(){N(a,f)},500)):fa()}})}}function fa(a){d.style.display="block";d.className="";d.innerHTML=wa;ua.className="";a&&a.last_time?d.onclick=function(){var f=a.last_time;delete a.last_time;N(a,f);delete d.onclick;d.className="n";d.innerHTML=xa}:(d.innerHTML=ya,d.className="e")}function s(a){return K["wallsearch-"+a]}function k(a,f){K["wallsearch-"+
a]=f}function D(a){return 10>1*a?"0"+a:a}function L(a){return a?a.replace(/<|>/g,function(a){return{"<":"&lt;",">":"&gt;"}[a]}):""}function E(a){return!0===a.checked?a.value:""}function b(a){return W.getElementById(a)}function ea(a,f){a.style.height="auto";var c=a.scrollHeight;a.style.height="0";za(a,"height",c,0,f)}function za(a,f,c,b,d){var g=1*new Date,h=a.style,k=setInterval(function(){var a=new Date-g,l=c*a/70+b;70<a&&(clearInterval(k),l=b+c,d&&setTimeout(function(){d()},10));h[f]=l+"px"},10)}
(function(a){var b=a.createElement("script");b.id="facebook-jssdk";b.async=!0;b.src="//connect.facebook.net/en_US/all.js";a.getElementsByTagName("head")[0].appendChild(b)})(W);ma.fbAsyncInit=function(){FB.init({appId:"168589393194273",channelUrl:"//atms.sakura.ne.jp/amidawars/index.php",status:!0,cookie:!0,xfbml:!0});var a=b("s");ea(a,function(){a.style.overflow="visible"});Q&&X()};var ba=b("w"),ta=b("o"),na=b("q"),ua=b("b"),T=b("d"),F=b("rm"),G=b("rf"),H=b("ra"),I=b("rs"),ga=b("lm"),ha=b("lf"),ia=
b("la"),ja=b("ls"),l=ga,Y=b("pn"),Z=b("ph"),$=b("pw"),sa=b("pm"),oa=b("ao"),pa=b("lo"),qa=b("os"),ra=b("ns"),d,wa="\u3082\u3063\u3068\u691c\u7d22\u3059\u308b",ya="\u691c\u7d22\u304c\u7d42\u4e86\u3057\u307e\u3057\u305f",S="\u3044\u3044\u306d\uff01",P="\u3044\u3044\u306d\u3092\u53d6\u308a\u6d88\u3059",Aa="\u3044\u3044\u306d\uff01\u306b\u5931\u6557\u3057\u307e\u3057\u305f\u3002\u6642\u9593\u3092\u7f6e\u3044\u3066\u3082\u3046\u4e00\u5ea6\u304a\u8a66\u3057\u304f\u3060\u3055\u3044\u3002",A,J,z,aa,g={me:{},
friends:{},all:{}},o='<article><img src="https://graph.facebook.com/,/picture" class="i" /><div><h2><a href="," target="_blank">,</a></h2><p>,</p>,<aside>,</aside><time>,</time><nav>\u00b7 <a href="," target="_blank" class="u">\u3082\u3063\u3068\u898b\u308b</a>\u00b7 <a href="http://www.facebook.com/sharer.php?u=," target="_blank" class="u">\u30b7\u30a7\u30a2</a>,</nav></div><a class="s," title="\u661f" name="," onclick="WS.star(this)">\u2605</a></article>'.split(","),ca=['\u00b7 <a href="javascript:void(0);" onclick="WS.like(\'',
"',this);\">","</a>"],B='<blockquote><a href="," target="_blank" class="h"><img src="," /></a><div><h3><a href="," target="_blank">,</a></h3><p>,</p></div></blockquote>'.split(","),O=['<blockquote><h2><a href="','" target="_blank">',"</a></h2><p>","</p></blockquote>"],C="<mark>$1</mark>",xa='<span class="a c"><span class="a1"></span><span class="a2"></span><span class="a3"></span></span>',Ca='<p id="e">'+xa+"</p>",Ba={"delete":S,post:P},M={me:'=me() AND permalink!=""',friends:"in(SELECT target_id FROM connection WHERE source_id=me())AND source_id!=me()",
all:"in(SELECT target_id FROM connection WHERE source_id=me())"},q,Da=864E5,da=!0,w=JSON,K=ma.localStorage,ka=!1;"ja_JP"!==LA&&(wa="More",ya="Search Exit.",S="Like",P="unlike",Aa="Like Failed. Please try again at intervals.",Ba={"delete":S,post:P});for(q in M)M[q]="SELECT post_id,actor_id,message,created_time,permalink,attachment,comments,likes FROM stream WHERE source_id "+M[q]+" AND is_hidden=0";if(K&&"object"===typeof w&&w.stringify&&w.parse){q=s("query");var U=s("range"),la=s("period");Q&&(q=
Q);R&&(U=R);q&&(na.value=q);if(U&&"me"!==U)switch(F.checked=!1,U){case "friends":G.checked=!0;l=ha;break;case "all":H.checked=!0;l=ia;break;default:I.checked=!0,l=ja}l.className="t";if(la&&""!==la)switch(Y.selected=!1,la){case "h":Z.selected=!0;break;case "w":$.selected=!0;break;default:sa.selected=!0}1==s("atonly")&&(oa.checked=!0);1==s("lionly")&&(pa.checked=!0);1==s("strict")&&(qa.checked=!0);1==s("nonstop")&&(ra.checked=!0)}else da=!1,I.disabled=!0,o[10]="</div></div></div></li>";b("y").onclick=
X;var V=function(a){X();l.className="";l=a;l.className="t"};F.onclick=ga.onclick=function(){V(ga)};G.onclick=ha.onclick=function(){V(ha)};H.onclick=ia.onclick=function(){V(ia)};I.onclick=ja.onclick=function(){V(ja)};b("v").onclick=function(){if(ka===false){ka=true;ea(T)}else{ka=false;za(T,"height",-T.scrollHeight,T.scrollHeight,void 0)}};(function(a){if(a)a.onclick=function(){location.hash=a.href;location.hash="";return false}})(b("pt"));return{like:function(a,b,c){b.disabled=true;if(g.me[a])c=g.me[a].likes.user_likes;
else if(g.friends[a])c=g.friends[a].likes.user_likes;else if(g.all[a])c=g.all[a].likes.user_likes;c=c===true?"delete":"post";FB.api("/"+a+"/likes",c,function(d){if(d&&!d.error){b.innerHTML=Ba[c];if(g.me[a])g.me[a].likes.user_likes=!g.me[a].likes.user_likes;if(g.friends[a])g.friends[a].likes.user_likes=!g.friends[a].likes.user_likes;if(g.all[a])g.all[a].likes.user_likes=!g.all[a].likes.user_likes}else alert(Aa);b.disabled=false});return false},star:function(a){var b=s("star"),c=a.name,b=b?w.parse(b):
{};if(a.className==="s"){a.className="s o";b[c]=aa[c]}else{a.className="s";delete b[c]}k("star",w.stringify(b))}}}(window,document);
